[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120

[tool.flake8]
max-line-length = 120
ignore = ['F401']

[tool.ruff]
line-length = 120
ignore = ['F401']

[tool.djlint]
profile = "django"
