# Generated by Django 5.0.2 on 2024-02-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                (
                    'gender',
                    models.CharField(
                        choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', 'Not Specified')],
                        max_length=50,
                    ),
                ),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                (
                    'gender',
                    models.CharField(
                        choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', 'Not Specified')],
                        max_length=50,
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.parent'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('monthly_fee', models.PositiveIntegerField()),
                ('exam_fee', models.PositiveIntegerField()),
                ('transportation_fee', models.PositiveIntegerField()),
                (
                    'student',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='student.student'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
