# Generated by Django 5.0.2 on 2024-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(default=7066147714, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='recieved_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
