# Generated by Django 5.0.2 on 2024-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_parent_phone_number_studentfee_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
