# Generated by Django 5.0.2 on 2024-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentfee_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='recieved_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
