# Generated by Django 5.0.2 on 2024-02-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentfee_recieved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='student.student'
            ),
        ),
    ]
