# Generated by Django 5.0.2 on 2024-02-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_parent_is_active_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('monthly_fee', models.PositiveIntegerField()),
                ('exam_fee', models.PositiveIntegerField()),
                ('transportation_fee', models.PositiveIntegerField()),
                (
                    'level',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('I', 'First'),
                            ('II', 'Second'),
                            ('III', 'Third'),
                            ('IV', 'Fourth'),
                            ('V', 'Fifth'),
                            ('VI', 'Sixth'),
                            ('VII', 'Seventh'),
                            ('VIII', 'Eighth'),
                            ('IX', 'Ninth'),
                            ('X', 'Tenth'),
                            ('XI', 'Eleventh'),
                            ('XII', 'Twelfth'),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('session', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='last_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('I', 'First'),
                    ('II', 'Second'),
                    ('III', 'Third'),
                    ('IV', 'Fourth'),
                    ('V', 'Fifth'),
                    ('VI', 'Sixth'),
                    ('VII', 'Seventh'),
                    ('VIII', 'Eighth'),
                    ('IX', 'Ninth'),
                    ('X', 'Tenth'),
                    ('XI', 'Eleventh'),
                    ('XII', 'Twelfth'),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(
                blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='month',
            field=models.CharField(
                blank=True,
                choices=[
                    ('jan', 'January'),
                    ('feb', 'February'),
                    ('mar', 'March'),
                    ('apr', 'April'),
                    ('may', 'May'),
                    ('jun', 'June'),
                    ('jul', 'July'),
                    ('aug', 'August'),
                    ('sept', 'September'),
                    ('oct', 'October'),
                    ('nov', 'November'),
                    ('dec', 'December'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
