# Generated by Django 5.0.2 on 2024-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_feestructure_student_discount_student_last_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='anual_session',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
