# Generated by Django 5.0.2 on 2024-02-18 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_feestructure_anual_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='anual_session',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='session',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='annual_session',
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code='invalid_registration',
                        message='Enter a valid session in the format 2023-2024',
                        regex='[0-9]{4}-[0-9]{4}',
                    )
                ],
            ),
        ),
    ]
