# Generated by Django 5.0.2 on 2024-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_feestructure_anual_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='monthly_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
