# Generated by Django 5.0.2 on 2024-02-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_feestructure_monthly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='exam_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transportation_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='exam_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='monthly_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='transportation_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
