# Generated by Django 5.0.2 on 2024-02-18 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_feestructure_exam_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
